language: python
os: windows
script:
  - pip install -r ./requirements.txt
  - ./build_executable
  - tar cvzf wizmem.tar.gz -C dist/ wizmem/
deploy:
  provider: releases
  file: wizmem.tar.gz
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  on:
    tags: true
